# source 'https://github.com/roxiemobile/shared-cocoa-frameworks.ios.git'
# source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

TAG_SWIFTCOMMONS = '1.2.4'

workspace '../RoxieMobile.ContentProviders/ContentProviders.xcworkspace'


target 'ContentProviders.SQLite' do
  project '../RoxieMobile.ContentProviders/Sources/SQLite/ContentProviders.SQLite.xcodeproj'

  # Dependencies
  pod 'CryptoSwift', '~> 0.8.3'
  pod 'SwiftCommonsConcurrent', git: 'https://github.com/roxiemobile/swift-commons.ios', tag: TAG_SWIFTCOMMONS, inhibit_warnings: true
  pod 'SwiftCommonsDiagnostics', git: 'https://github.com/roxiemobile/swift-commons.ios', tag: TAG_SWIFTCOMMONS, inhibit_warnings: true
  pod 'SwiftCommonsObjC', git: 'https://github.com/roxiemobile/swift-commons.ios', tag: TAG_SWIFTCOMMONS, inhibit_warnings: true
  pod 'SwiftCommonsExtensions', git: 'https://github.com/roxiemobile/swift-commons.ios', tag: TAG_SWIFTCOMMONS, inhibit_warnings: true
  pod 'SwiftCommonsLang', git: 'https://github.com/roxiemobile/swift-commons.ios', tag: TAG_SWIFTCOMMONS, inhibit_warnings: true
  pod 'SwiftCommonsLogging', git: 'https://github.com/roxiemobile/swift-commons.ios', tag: TAG_SWIFTCOMMONS, inhibit_warnings: true
  pod 'SwiftCommonsAbstractions', git: 'https://github.com/roxiemobile/swift-commons.ios', tag: TAG_SWIFTCOMMONS, inhibit_warnings: true
  pod 'SwiftCommonsData', git: 'https://github.com/roxiemobile/swift-commons.ios', tag: TAG_SWIFTCOMMONS, inhibit_warnings: true
  pod 'SwiftCommons', git: 'https://github.com/roxiemobile/swift-commons.ios', tag: TAG_SWIFTCOMMONS, inhibit_warnings: true
  pod 'SQLite.swift/SQLCipher', '~> 0.11.4'

end
